### ISSUE TITLE
Compilation of downstream DAGMC fails on find_volume

### ISSUE THREAD

**Issue by ebknudsen** [pshriwise/double-down#40] opened 2023-08-16 15:27 UTC
Possibly off-topic, but when compiling DAGMC against  double-down, some recent addition to DAGMC trips the compile with an error on find_volume not being defined.
E.g.
`cmake .. -DMOAB_DIR=$HOME/openmc-0.13.4-dev -DDOUBLE_DOWN=on -DDOUBLE_DOWN_DIR=$HOME/openmc-0.13.4-dev`
leads to:
```
/home/erkn/dagmc/src/dagmc/DagMC.cpp: In member function ‘moab::ErrorCode moab::DagMC::find_volume(const double*, moab::EntityHandle&, const double*)’:
/home/erkn/dagmc/src/dagmc/DagMC.cpp:818:32: error: ‘class double_down::RayTracingInterface’ has no member named ‘find_volume’
  818 |   ErrorCode rval = ray_tracer->find_volume(xyz, volume, uvw);
```
whereas
`cmake .. -DMOAB_DIR=$HOME/openmc-0.13.4-dev -DDOUBLE_DOWN=off -DDOUBLE_DOWN_DIR=$HOME/openmc-0.13.4-dev`
compiles fine.

A wild guess is that perhaps the find_volume feature is not yet exposed through double-down. OTOH the problem might be elsewhere in DAGMC.

**Comment by ebknudsen** [comment] 2023-08-16 23:38
Upon a bit more inspection it seems that the problem is that the moab::find_volume function is simply not exposed in double_down's RayTracingInterface class at present. This could be easily solved I think.

**Comment by ahnaf-tahmid-chowdhury** [comment] 2023-12-08 17:40
I have noticed the issue is fixed in the `develop` branch.

**Closed as completed** 2023-12-08 18:10 UTC
